#Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
#Fabric Properties
minecraft_version=26.3
minecraft_version_range=~26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_id=odin
mod_name=Odin
mod_description=A Hypixel Skyblock QoL mod
mod_version=0.3.4
maven_group=com.odtheking
archives_base_name=odin-fabric
# Mod Dependencies
fabric_kotlin_version=1.14.1+kotlin.2.4.20
fabric_api_version=0.160.5+26.3
modmenu_version=21.0.0-beta.1
devauth_version=1.2.2
commodore_version=1.0.1
iris=1.11.5+26.3-fabric
# Other Properties
kotlin_version=2.4.0
kotlin.code.style=official
